### PR TITLE
feat: support series in response serializer

### LINKED ISSUE #918: Code generation crash on question "Give me full names  of people was in class 3 grouped by second name"
### System Info

pandas AI 1.5.17

### 🐛 Describe the bug

I have a table with column Name and ask question "Give me full names  of people was in class 3 grouped by second name". And I see this crash. 

Data is Titanik data set.
[titanic.csv](https://github.com/gventuri/pandas-ai/files/14113732/titanic.csv)

Log:

```
Question: Give me full names  of people was in class 3 grouped by second name
Running PandasAI with openai LLM...
Prompt ID: 388d3d15-3cbc-43be-b26b-c59b1b56fa9c
<class 'pandasai.helpers.output_types._output_types.DefaultOutputType'> is going to be used.
<class 'pandasai.helpers.viz_library_types._viz_library_types.NoVizLibraryType'> is going to be used.
Executing Step 0: CacheLookup
Executing Step 1: PromptGeneration
Using prompt: <dataframe>
dfs[0]:891x12
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,,S
</dataframe>




Update this initial code:
python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var: type (possible values "string", "number", "dataframe", "plot"). Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" }

Q: Give me full names  of people was in class 3 grouped by second name
Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.



Generate python code and return full updated code:
Executing Step 2: CodeGenerator
Code generated:
            
            # TODO: import the required dependencies
import pandas as pd

# Write code here
df = dfs[0]
class_3_names = df[df['Pclass'] == 3]['Name']
full_names = class_3_names.apply(lambda x: x.split(',')[1].strip())
grouped_names = full_names.groupby(full_names).apply(lambda x: ', '.join(x))
result = {"type": "dataframe", "value": grouped_names}

result
            

Executing Step 3: CachePopulation
Executing Step 4: CodeExecution

Code running:

df = dfs[0]
class_3_names = df[df['Pclass'] == 3]['Name']
full_names = class_3_names.apply(lambda x: x.split(',')[1].strip())
grouped_names = full_names.groupby(full_names).apply(lambda x: ', '.join(x))
result = {'type': 'dataframe', 'value': grouped_names}
result
        
Failed to execute code with a correction framework [retry number: 1]
Failed with error: Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 53, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 134, in execute_func
    step_data = self._generate_exec_step(tag, result)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 183, in _generate_exec_step
    self._response = self._format_response(result)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 198, in _format_response
    df_dict = self.convert_dataframe_to_dict(result["value"])
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 93, in convert_dataframe_to_dict
    return {"headers": json_data["columns"], "rows": json_data["data"]}
KeyError: 'columns'
. Retrying
Using prompt: <dataframe>
dfs[0]:891x12
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,,S
</dataframe>

The user asked the following question:
Q: Give me full names  of people was in class 3 grouped by second name

You generated this python code:
# TODO: import the required dependencies
import pandas as pd

# Write code here
df = dfs[0]
class_3_names = df[df['Pclass'] == 3]['Name']
full_names = class_3_names.apply(lambda x: x.split(',')[1].strip())
grouped_names = full_names.groupby(full_names).apply(lambda x: ', '.join(x))
result = {"type": "dataframe", "value": grouped_names}

result

It fails with the following error:
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 53, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 134, in execute_func
    step_data = self._generate_exec_step(tag, result)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 183, in _generate_exec_step
    self._response = self._format_response(result)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 198, in _format_response
    df_dict = self.convert_dataframe_to_dict(result["value"])
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 93, in convert_dataframe_to_dict
    return {"headers": json_data["columns"], "rows": json_data["data"]}
KeyError: 'columns'


Fix the python code above and return the new python code:

Code running:

df = dfs[0]
class_3_names = df[df['Pclass'] == 3]['Name']
full_names = class_3_names.apply(lambda x: x.split(',')[1].strip())
grouped_names = full_names.groupby(full_names).apply(lambda x: ', '.join(x))
result = {'type': 'dataframe', 'value': grouped_names.reset_index()}
result
        
Failed to execute code with a correction framework [retry number: 2]
Failed with error: Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 53, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 212, in execute_code
    exec(code_to_run, environment)
  File "<string>", line 5, in <module>
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/core/series.py", line 1581, in reset_index
    return df.reset_index(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 6361, in reset_index
    new_obj.insert(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 4817, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert Name, already exists
. Retrying
Using prompt: <dataframe>
dfs[0]:891x12
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,,S
</dataframe>

The user asked the following question:
Q: Give me full names  of people was in class 3 grouped by second name

You generated this python code:
# TODO: import the required dependencies
import pandas as pd

# Write code here
df = dfs[0]
class_3_names = df[df['Pclass'] == 3]['Name']
full_names = class_3_names.apply(lambda x: x.split(',')[1].strip())
grouped_names = full_names.groupby(full_names).apply(lambda x: ', '.join(x))
result = {"type": "dataframe", "value": grouped_names}

result

It fails with the following error:
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 53, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 212, in execute_code
    exec(code_to_run, environment)
  File "<string>", line 5, in <module>
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/core/series.py", line 1581, in reset_index
    return df.reset_index(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 6361, in reset_index
    new_obj.insert(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 4817, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert Name, already exists


Fix the python code above and return the new python code:

Code running:

df = dfs[0]
class_3_names = df[df['Pclass'] == 3]['Name']
full_names = class_3_names.apply(lambda x: x.split(',')[1].strip())
grouped_names = full_names.groupby(full_names).apply(lambda x: ', '.join(x)).reset_index()
result = {'type': 'dataframe', 'value': grouped_names}
result
        
Pipeline failed on step 4: cannot insert Name, already exists
```

### PR DESCRIPTION
**Pull request by oedokumaci**
- [x] Closes #918.
- [x] Tests added and passed if fixing a bug or adding a new feature.
- [x] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

### CODE REVIEW

**Comment by gventuri** [comment]
@oedokumaci thanks a lot for the fix, really appreciated!

**Comment by oedokumaci** [comment]
Ruffed your test and squashed those two commits, should pass ci now. Thanks!

**Comment by gventuri** [comment]
@oedokumaci it's weird, but the pipeline fails consistently at the coverage stage on python 3.11. Will look into it, but have no idea of what's going wrong there!

**Comment by oedokumaci** [comment]
Noticed the same thing but thought either it's fine or that you'd know what's going on 😄

**Comment by oedokumaci** [comment]
https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
@gventuri

**Comment by gventuri** [comment]
@oedokumaci merging it as the CI runs ok, if it breaks the pipeline in main we'll figure out how to fix it!

**Pull request merged**
