### PR TITLE
chore(llm): major refactor of VertexAI models

### PR DESCRIPTION
**Pull request by mspronesti**
Hi @gventuri, 
this PR aims at refactoring VertexAI models. In particular, at only initializing the client once - not at every generation. Also, I'm allowing the user to explicitly pass the credentials for their GCP account. Lastly, I removed some unneeded checks and validations.

- [X] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

### Summary by CodeRabbit

- New Feature: Added support for Google Vertex AI in the `GoogleVertexAI` class, including initialization with custom credentials.
- Refactor: Simplified the text generation process in the `GoogleVertexAI` class by using the `predict` method of the Vertex AI client.
- Test: Updated tests for the `GoogleVertexAI` class to include mocking of model loading and validation of model types.
- Bug Fix: Improved error handling in the `GoogleVertexAI` class by raising an exception when an unsupported or no model is provided.

### CODE REVIEW

**Comment by gventuri** [comment]
@mspronesti tried it but for some reason it doesn't work. It is like blocking at some point when we instantiate it. Haven't investigate further, happy to debug more if it doesn't apply on your machine!

**Comment by gventuri** [comment]
@mspronesti I finally got an error:

google.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling target function, last exception: 503 Getting 

Here's how I instantiate it:

```
llm = GoogleVertexAI(
    project_id="xxxxx",
    location="us-central1",
    model="code-bison"
)
```

**Comment by mspronesti** [comment]
@gventuri I can't reproduce the error :/ Do you also have it with text models?

**Comment by gventuri** [comment]
@mspronesti same error with any model :( Are you instantiating in a similar way to what I do?
Just for context, I am logged in with the gcloud cli, don't know if it makes a difference

**Comment by mspronesti** [comment]
@gventuri Do you happen to have a longer stack trace?

**Comment by gventuri** [comment]
Not really, that's all I have. I can try to debug further and catch the whole traceback. I've retried with the old version and seems to work, so I'm quite sure it's being affected by some changes. I'll try to investigate further.

**Comment by mspronesti** [comment]
I'm off for a few days. I will debug the issue next week unless you figure it out first :)

**Comment by gventuri** [comment]
@mspronesti sure, I'll try to look into it! :)

**Pull request closed without merging**
