### PR TITLE
fix(agent): langchain LLM instantiation

### LINKED ISSUE #976: Doesn't work in AzureOpenAI
### System Info

OS version: win10
Python version: python 3.11
Code：
from pandasai import SmartDataframe
from langchain_openai import AzureChatOpenAI
import pandas as pd
import os

os.environ["PANDASAI_API_KEY"] = "......BTn6"
**llm = AzureChatOpenAI(
openai_api_key=config.azure_openai_api_key,
openai_api_version=config.azure_openai_api_version,
azure_endpoint=config.azure_openai_endpoint,
azure_deployment=config.model_name
)**
sales_by_country = pd.DataFrame({
"country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
"sales": [5000, 3200, 2900, 4100, 2300, 2100, 2500, 2600, 4500, 7000]
})
df = SmartDataframe(sales_by_country, config={"llm": llm})
response = df.chat('Which are the top 5 countries by sales?')
print(response)

### 🐛 Describe the bug

Traceback (most recent call last):
  File "D:\Projects\dataCopilot-web\333.py", line 165, in <module>
    agent = Agent(
            ^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pandasai\agent\base.py", line 74, in __init__
    config = self.get_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pandasai\agent\base.py", line 147, in get_config
    config = Config(**config)
             ^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\main.py", line 1074, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\fields.py", line 895, in validate
    v, errors = self._apply_validators(v, values, loc, cls, self.post_validators)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\fields.py", line 1154, in _apply_validators
    v = validator(cls, v, values, self, self.model_config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\class_validators.py", line 304, in <lambda>
    return lambda cls, v, values, field, config: validator(cls, v)
                                                 ^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pandasai\schemas\df_config.py", line 41, in validate_llm
    raise LLMNotFoundError("LLM is required")
pandasai.exceptions.LLMNotFoundError: LLM is required

### PR DESCRIPTION
**Pull request by mspronesti**
- [X] Closes #976

### CODE REVIEW

**Comment by Rainismer** [comment]
@mspronesti I just tried it and it still gives me same error.

**Comment by mspronesti** [comment]
@Rainismer can you list your steps here?

**Comment by Rainismer** [comment]
@mspronesti 

from pandasai import SmartDataframe
import pandas as pd
from langchain_openai import AzureChatOpenAI

llm = AzureChatOpenAI(...)

sales_by_country = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "sales": [5000, 3200, 2900, 4100, 2300, 2100, 2500, 2600, 4500, 7000]
})

df = SmartDataframe(sales_by_country, config={"llm": llm})

response = df.chat('Which are the top 5 countries by sales?')
print(response)

###########################################################

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject2\sk.py", line 18, in <module>
    df = SmartDataframe(sales_by_country, config={"llm": llm})
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\smart_dataframe\__init__.py", line 64, in __init__
    self._agent = Agent([df], config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\agent\base.py", line 74, in __init__
    config = self.get_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\agent\base.py", line 147, in get_config
    config = Config(**config)
             ^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1076, in pydantic.main.validate_model
  File "pydantic\fields.py", line 898, in pydantic.fields.ModelField.validate
  File "pydantic\fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
  File "pydantic\class_validators.py", line 304, in pydantic.class_validators._generic_validator_cls.lambda4
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\schemas\df_config.py", line 41, in validate_llm
    raise LLMNotFoundError("LLM is required")
pandasai.exceptions.LLMNotFoundError: LLM is required

**Comment by Rainismer** [comment]
@mspronesti I reinstalled pandasai from this branch.

############################################

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\pipelines\chat\generate_chat_pipeline.py", line 155, in run
    output = self.pipeline.run(input)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\pipelines\pipeline.py", line 137, in run
    raise e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\pipelines\pipeline.py", line 101, in run
    step_output = logic.execute(
                  ^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\pipelines\chat\code_generator.py", line 33, in execute
    code = pipeline_context.config.llm.generate_code(input, pipeline_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\llm\base.py", line 196, in generate_code
    response = self.call(instruction, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandasai\llm\langchain.py", line 55, in call
    res = self.langchain_llm.invoke(prompt)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\chat_models.py", line 166, in invoke
    self.generate_prompt(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\chat_models.py", line 544, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\chat_models.py", line 408, in generate
    raise e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\chat_models.py", line 398, in generate
    self._generate_with_cache(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\chat_models.py", line 577, in _generate_with_cache
    return self._generate(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_openai\chat_models\base.py", line 451, in _generate
    response = self.client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_utils\_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\resources\chat\completions.py", line 659, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 1180, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 869, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py", line 960, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
Unfortunately, I was not able to answer your question, because of the following error:

Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**Comment by mspronesti** [comment]
@Rainismer This is an error with your AzureOpenAI instantiation. Please double check you have set all the required variables. 

```py
import os

import pandas as pd
from langchain_openai import AzureChatOpenAI

from pandasai import SmartDataframe

# os.environ["PANDASAI_API_KEY"] = "......BTn6"

os.environ["AZURE_OPENAI_API_KEY"] = "YOUR KEY HERE" # set this
os.environ["AZURE_OPENAI_ENDPOINT"] = "YOUR ENDPOINT HERE" # set this
os.environ["OPENAI_API_VERSION"] = "2023-12-01-preview"

llm = AzureChatOpenAI(azure_deployment="YOUR MODEL DEPLOYMENT") # set this
sales_by_country = pd.DataFrame(
    {
        "country": [
            "United States",
            "United Kingdom",
            "France",
            "Germany",
            "Italy",
            "Spain",
            "Canada",
            "Australia",
            "Japan",
            "China",
        ],
        "sales": [5000, 3200, 2900, 4100, 2300, 2100, 2500, 2600, 4500, 7000],
    }
)
df = SmartDataframe(sales_by_country, config={"llm": llm, "enable_cache": False})
response = df.chat("Which are the top 5 countries by sales?")
print(response)
```

**Comment by Rainismer** [comment]
@mspronesti This is an error with "2024-2-15-preview", it should be "2024-02-15-preview", it can work now. thanks!
By the way,  Is Polars DataFrame available yet?

**Comment by mspronesti** [comment]
@Rainismer Glad it works :) @gventuri I suppose you can review this then.

Regarding the second question, polars should work afaik. If you were to face any errors with polars, feel free to open an issue (or a pull request if you were to spot any bugs)

**Comment by Rainismer** [comment]
@mspronesti I just I tried polars dataframe, why is there no border line?
image

**Comment by mspronesti** [comment]
@Rainismer not sure I got the question :sweat_smile:  However, I recommend opening a discussion if you don't mind, as we are going off-topic here :)

**Comment by gventuri** [comment]
Wow, thanks a lot for the quick fix! Great job @mspronesti, merging!

**Pull request merged**
