### PR TITLE
Fix (cx_Oracle.DatabaseError) ORA-00904

### LINKED ISSUE #1160: (cx_Oracle.DatabaseError) ORA-00904: "RAND": invalid identifier
### System Info

OS version: Microsoft Windows 11 Pro, 10.0.22631 Build 22631
Python version: 3.10.4
pandas-ai version: 2.0.42

### 🐛 Describe the bug

Unfortunately, I was not able to get your answers, because of the following error:

(cx_Oracle.DatabaseError) ORA-00904: "RAND": invalid identifier
[SQL: SELECT * 
FROM TABLE ORDER BY RAND() ASC
 FETCH FIRST 3 ROWS ONLY]
(Background on this error at: https://sqlalche.me/e/20/4xp6)

### PR DESCRIPTION
**Pull request by eaandersen**
- [X] Closes #1160
- [X] Tests passed, No Tests added to TestSQLConnector.
- [X] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

### CODE REVIEW

**Comment by gventuri** [comment]
@eaandersen thanks a lot for the PR. To keep it cleaner, would you mind creating a Oracle connector extending the SQL connector that overrides the default value for rand? That would be a cleaner and easier to maintain solution.

**Comment by eaandersen** [comment]
> @eaandersen thanks a lot for the PR. To keep it cleaner, would you mind creating a Oracle connector extending the SQL connector that overrides the default value for rand? That would be a cleaner and easier to maintain solution.

It makes perfect sense to extend the SQLConnector and create a separate class for Oracle. I'll send an update in the next day or two.

**Comment by gventuri** [comment]
@eaandersen thanks a lot, really appreciated!

**Comment by eaandersen** [comment]
> @eaandersen thanks a lot, really appreciated!

Updates completed. I created a separate class for Oracle, extending the SQL connector. Added required unit tests and everything passed. Also added a check for connection close to avoid NoneType errors. Updated TOML with optional cx_Oracle. Let me know if you're okay with these changes.

**Comment by gventuri** [comment]
@eaandersen thanks a lot for the changes, seems good. Running the CI, will merge as soon as it passes!

**Pull request merged**
