### PR TITLE
Upgrade Modin and pandas versions

### LINKED ISSUE #1085: Pandas 2.0 conflicts with the SQL connectors
### System Info

OS version: any
Python version: any
pandasai: any

### 🐛 Describe the bug

Our current setup is facing issues when attempting to upgrade to pandas versions beyond 2.0, as this update seems to interfere with the functionality of our SQL connectors. It's essential for us to delve into the root cause of this problem to identify a viable solution. This will enable us to successfully transition to a more recent version of pandas, as well as to the latest version of modin.

### PR DESCRIPTION
**Pull request by YarShev**
- [x] Closes #1085 (Replace xxxx with the GitHub issue number).
- [x] Tests passed if fixing a bug or adding a new feature.
- [x] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

### CODE REVIEW

**Comment by YarShev** [comment]
Hey folks, I tried to upgrade Modin and pandas versions to latest once again as I didn't see any error in tests locally. Let's see how CI goes.

**Comment by gventuri** [comment]
@YarShev IIRC, the issues were with the SnowFlake connector and probably others as well, but I'm not sure it is highlighted from the tests, as it might be mocked (which is not good, as there should be an error failing because of that, but I'm afraid we don't have a test for that yet).

**Comment by YarShev** [comment]
@gventuri, how did you figure out that there is an issue with the Snowflake connector? Is there an open issue a user filed on this matter?

**Comment by gventuri** [comment]
@ArslanSaleem initially reported it. Maybe he can elaborate further!

**Comment by sfc-gh-mvashishtha** [comment]
> Maybe he can elaborate further!

Let's follow up on #1085.

**Pull request closed without merging**
