### PR TITLE
Added Poe-api as LLM reference

### PR DESCRIPTION
**Pull request by Iamprashanth-1**
- [x] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] Tests added and passed if fixing a bug or adding a new feature
- [x] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

### CODE REVIEW

**Comment by Iamprashanth-1** [comment]
Adding Poe-api support because people don't have billing on their account or their API limit is exceeded they use this poe-api

@gventuri

**Review by mspronesti — COMMENTED** [review]
Have you tried to run this ? I get a `AttributeError: 'NoneType' object has no attribute 'group'` (same specifying `formkey`, same installing `poe` with `-U`). 

Besides, this implementation contains quite a lot of leftovers from your copy-paste of the gpt4all PR and some encapsulation mistakes. If you have a fix for the first problem (which seems to be a known issue, see [here](https://github.com/ading2210/poe-api/issues/202)), I will be happy to leave a more detailed review.

**Comment by Iamprashanth-1** [comment]
can you let me know which bot have you tried? mostly it works well with Assiatnt and ChatGpt

**Comment by mspronesti** [comment]
I tried chinchilla, but the problem's not there. This simple snippet fails for me 
```py
import poe

token=...
formkey=...

client = poe.Client(token=token, formkey=formkey)
```

There are multiple issues reporting the same failed I mentioned in my previous comment. Seems to be something recurrent. Have a look [here](https://github.com/ading2210/poe-api/issues?q=is%3Aissue+AttributeError%3A+%27NoneType%27+object+has+no+attribute+%27group%27)

**Comment by Iamprashanth-1** [comment]
Here Is the example:

from pandasai import PandasAI
from pandasai.llm.poe_api import POEAPI

llm = POEAPI(bot_name='chinchilla',token = '')
pandas_ai = PandasAI(llm,enable_cache=False , )
pandas_ai([df_tweets, df_tweet_users], "What are the top tweets?")

Just try this once:

don't need to provide formkey

**Comment by mspronesti** [comment]
As explained above, it does not work for me neither with nor without the `formkey`. Also, to use your snippet I would need the dataframes :-) 
I used the `from_dataframe` example available in this repository replacing the `llm` and it yields the named error.

**Comment by Iamprashanth-1** [comment]
but when I tried It's working fine. can you check your poe.com account whether promt is available in respective bot

**Comment by mspronesti** [comment]
Of course. An invalid or missing token in poe api would raise the following error`RuntimeError: Invalid or missing token.` which is not the case for me. Anyway if it might be a problem with my setup, I let somebody else try this and give you feedback (even if that seems to be a very common problem among the poe api community).
If Gabriele wants to merge your PR, I will be happy to leave it a more thorough review.

**Comment by Iamprashanth-1** [comment]
Can you update poe-api package to latest version and try once

**Pull request closed without merging**
