### PR TITLE
fix: multi-round conversion with Bedrock Claude

### PR DESCRIPTION
**Pull request by goriri**
- [x] Tests added and passed if fixing a bug or adding a new feature.
- [x] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

### CODE REVIEW

**Comment by gventuri** [comment]
@goriri can you provide slightly more context about this fix? I don't understand exactly why we are overriding the previous message in the conversation. Does bedrock raise an error if there are 2 user messages in a row?

**Comment by gventuri** [comment]
@goriri let me know, so we can merge :)

**Comment by goriri** [comment]
@gventuri 
yes. it will complain when two user messages in a row (requiring alternating user/assistant messages). in a single message, the content can contain multiple text sections.

**Comment by gventuri** [comment]
Thanks a lot for letting me know, merging! @goriri

**Pull request merged**
