### PR TITLE
Add support for Ollama, Bedrock, Sagemaker, Replicate, VLLM, Palm, Claude-2, Cohere, Replicate Llama2 CodeLlama (100+LLMs) 

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM is a lightweight package to simplify LLM API calls - use any llm as a drop in replacement for gpt-3.5-turbo. 

Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)

# hugging face
response = completion(model="huggingface/WizardLM/WizardCoder-Python-34B-V1.0",  messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Hi @gventuri can you please take a look at this PR when possible ?

**Comment by alifzl** [comment]
hey @ishaan-jaff today I tried to integrate pandas-ai with [this](https://hub.docker.com/r/litellm/ollama). but I found that `pandasai/llm/base.py` file is changed significantly. can you advise in this regard? I want to integrate pandas with some local litellm+Ollama. thanks

**Comment by Edu126** [comment]
Has anyone tried to use the endpoint for Ollam as the Hungging face inference server?

**Comment by rustem-dev** [comment]
> hey @ishaan-jaff today I tried to integrate pandas-ai with [this](https://hub.docker.com/r/litellm/ollama). but I found that `pandasai/llm/base.py` file is changed significantly. can you advise in this regard? I want to integrate pandasai with local litellm+Ollama. thanks

I wonder if I can help with this. I know many people around me who tried pandasai with Ollama locally but failed. I was able to execute this without langchain.llm or pandas.llm simply importing openai with exposed LiteLLM endpoint but lack of integration with smartdataframe and `chat` class it's worthless for now.

**Comment by alifzl** [comment]
> > hey @ishaan-jaff today I tried to integrate pandas-ai with [this](https://hub.docker.com/r/litellm/ollama). but I found that `pandasai/llm/base.py` file is changed significantly. can you advise in this regard? I want to integrate pandasai with local litellm+Ollama. thanks
> 
> I wonder if I can help with this. I know many people around me who tried pandasai with Ollama locally but failed. I was able to execute this without langchain.llm or pandas.llm simply importing openai with exposed LiteLLM endpoint but lack of integration with smartdataframe and `chat` class makes it worthless for now.

Yeah me too, i was tried to do the same some time ago and faced the same result.

**Pull request closed without merging**
